In [33]:
import pandas as pd

In [97]:
dataF = {
    'tweet_text': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'],
}
data = pd.DataFrame(dataF)

In [100]:
def call_llm():
    a="[positive|iPad|Apple|Technology|United States|Texas][positive|Holler Gram|HollerGram|Software|United States|Texas][positive|SXSW Go|SXSW|Event|United States|Texas]"
    return a

In [99]:
input_tweet=[]
itera=0
for i in range(0,len(data)):
    input_tweet.append( str(data['tweet_text'].iloc[i]))
    if(len(input_tweet)==3):
        itera=i
        result_array = call_llm()
        output_array=result_array.split(sep="][")
        for j in output_array:
            print(itera)
            for i in range(itera, itera-3, -step):
                data.loc[i,'Output_tweet'] = j
                #print(i)
        input_tweet.clear()

2
2
2
5
5
5
8
8
8
11
11
11

In [37]:
data

    tweet_text                                      Output_tweet
 0           a  positive|SXSW Go|SXSW|Event|United States|Texas]
 1           b  positive|SXSW Go|SXSW|Event|United States|Texas]
 2           c  positive|SXSW Go|SXSW|Event|United States|Texas]
 3           d  positive|SXSW Go|SXSW|Event|United States|Texas]
 4           e  positive|SXSW Go|SXSW|Event|United States|Texas]
 5           f  positive|SXSW Go|SXSW|Event|United States|Texas]
 6           g  positive|SXSW Go|SXSW|Event|United States|Texas]
 7           h  positive|SXSW Go|SXSW|Event|United States|Texas]
 8           i  positive|SXSW Go|SXSW|Event|United States|Texas]
 9           j  positive|SXSW Go|SXSW|Event|United States|Texas]
 10          k                                               NaN
 11          l                                               NaN
 12          m                                               NaN
 13          n                                               NaN
-1         NaN  positive|SXSW Go|SXSW|Event|United States|Texas]
-2         NaN  positive|SXSW Go|SXSW|Event|United States|Texas]

In [26]:
itera = 10
step = 1

for i in range(itera, itera-3, -step):
    print(i)

10
9
8

In [101]:
#output_array,2
def addreversed(output_array,itera):
    for value in reversed(output_array):
        #print(value)
        #print(itera)
        data.loc[itera,'Output_tweet'] = value
        itera=itera-1

In [109]:
input_tweet=[]
output_array=[]
itera=0
for i in range(0,len(data)):
    input_tweet.append( str(data['tweet_text'].iloc[i]))
    if(len(input_tweet)==3):
        itera=i
        result_array = call_llm()
        output_array=result_array.split(sep="][")
        addreversed(output_array,itera)
        input_tweet.clear()
    elif (len(data)-i)==1 or (len(data)-1)==2 :
        #print("Inside loop")
        itera=i
        result_array = call_llm()
        output_array=result_array.split(sep="][")
        addreversed(output_array,itera)
        input_tweet.clear()

positive|SXSW Go|SXSW|Event|United States|Texas]
2
positive|Holler Gram|HollerGram|Software|United States|Texas
1
[positive|iPad|Apple|Technology|United States|Texas
0
positive|SXSW Go|SXSW|Event|United States|Texas]
5
positive|Holler Gram|HollerGram|Software|United States|Texas
4
[positive|iPad|Apple|Technology|United States|Texas
3
positive|SXSW Go|SXSW|Event|United States|Texas]
8
positive|Holler Gram|HollerGram|Software|United States|Texas
7
[positive|iPad|Apple|Technology|United States|Texas
6
positive|SXSW Go|SXSW|Event|United States|Texas]
11
positive|Holler Gram|HollerGram|Software|United States|Texas
10
[positive|iPad|Apple|Technology|United States|Texas
9
Inside loop
positive|SXSW Go|SXSW|Event|United States|Texas]
13
positive|Holler Gram|HollerGram|Software|United States|Texas
12
[positive|iPad|Apple|Technology|United States|Texas
11

In [75]:
output_array

['[positive|iPad|Apple|Technology|United States|Texas',
 'positive|Holler Gram|HollerGram|Software|United States|Texas',
 'positive|SXSW Go|SXSW|Event|United States|Texas]',
 'positive|iPad|Apple|Technology|United States|Texas',
 'positive|Holler Gram|HollerGram|Software|United States|Texas',
 'positive|SXSW Go|SXSW|Event|United States|Texas']

In [110]:
data

   tweet_text                                       Output_tweet
0           a  [positive|iPad|Apple|Technology|United States|...
1           b  positive|Holler Gram|HollerGram|Software|Unite...
2           c   positive|SXSW Go|SXSW|Event|United States|Texas]
3           d  [positive|iPad|Apple|Technology|United States|...
4           e  positive|Holler Gram|HollerGram|Software|Unite...
5           f   positive|SXSW Go|SXSW|Event|United States|Texas]
6           g  [positive|iPad|Apple|Technology|United States|...
7           h  positive|Holler Gram|HollerGram|Software|Unite...
8           i   positive|SXSW Go|SXSW|Event|United States|Texas]
9           j  [positive|iPad|Apple|Technology|United States|...
10          k  positive|Holler Gram|HollerGram|Software|Unite...
11          l  [positive|iPad|Apple|Technology|United States|...
12          m  positive|Holler Gram|HollerGram|Software|Unite...
13          n   positive|SXSW Go|SXSW|Event|United States|Texas]