In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import math

In [2]:
df=pd.read_csv('data.csv')

In [134]:
df.shape

(6819, 96)

In [135]:
df['Bankrupt?'].value_counts()

0    6599
1     220
Name: Bankrupt?, dtype: int64

In [136]:
df.head()

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490

In [3]:
Q1 = df.quantile(0.01)
Q3 = df.quantile(0.99)
IQR = Q3 - Q1
df = df[~((df < (Q1-6*IQR)) | (df > (Q3 + 6*IQR))).any(axis = 1)]

In [4]:
df.shape

(6552, 96)

In [139]:
df['Bankrupt?'].value_counts()

0    6369
1     183
Name: Bankrupt?, dtype: int64

In [73]:
#df_scale=df.drop(columns='Bankrupt?')

In [5]:
minmax=MinMaxScaler()

In [6]:
df_scaled=minmax.fit_transform(df)

In [7]:
df_scaled=pd.DataFrame(data=df_scaled,columns=df.columns)

In [8]:
df_scaled.head()

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1.0,0.381454,0.420377,0.405750,0.709830,0.707021,0.912856,0.550915,0.523433,0.411011,...,0.650414,0.009119,0.459292,0.709820,0.796851,0.135752,0.260955,0.527779,0.0,0.009952
1,1.0,0.411561,0.447439,0.457733,0.628209,0.625724,0.880983,0.555418,0.533724,0.443784,...,0.680432,0.003151,0.459534,0.628201,0.850553,0.060711,0.261897,0.530599,0.0,0.023846
2,1.0,0.478649,0.535214,0.522298,0.697649,0.694889,0.913320,0.577930,0.555996,0.449630,...,0.753743,0.003776,0.462408,0.697648,0.892175,0.032330,0.242818,0.580957,0.0,0.045126
3,1.0,0.400070,0.411100,0.419134,0.658415,0.656169,0.887885,0.551820,0.520878,0.432889,...,0.641922,0.005177,0.457961,0.658427,0.813014,0.090494,0.261688,0.530023,0.0,0.015621
4,0.0,0.402378,0.441840,0.436158,0.794077,0.790935,0.915685,0.557954,0.533381,0.418841,...,0.676552,0.018272,0.463062,0.794080,0.813336,0.156123,0.261168,0.528468,0.0,0.008462

In [9]:
df_scaled.columns = df_scaled.columns.str.strip()
df_scaled.columns = df_scaled.columns.str.replace(" " ,"_")
df_scaled.rename(columns = {'Bankrupt?' :'Bankrupt' },inplace=True)

In [144]:
df_scaled.shape

(6552, 96)

In [145]:
df_scaled.head()

,Bankrupt,ROA(C)_before_interest_and_depreciation_before_interest,ROA(A)_before_interest_and_%_after_tax,ROA(B)_before_interest_and_depreciation_after_tax,Operating_Gross_Margin,Realized_Sales_Gross_Margin,Operating_Profit_Rate,Pre-tax_net_Interest_Rate,After-tax_net_Interest_Rate,Non-industry_income_and_expenditure/revenue,...,Net_Income_to_Total_Assets,Total_assets_to_GNP_price,No-credit_Interval,Gross_Profit_to_Sales,Net_Income_to_Stockholder's_Equity,Liability_to_Equity,Degree_of_Financial_Leverage_(DFL),Interest_Coverage_Ratio_(Interest_expense_to_EBIT),Net_Income_Flag,Equity_to_Liability
0,1.0,0.381454,0.420377,0.405750,0.709830,0.707021,0.912856,0.550915,0.523433,0.411011,...,0.650414,0.009119,0.459292,0.709820,0.796851,0.135752,0.260955,0.527779,0.0,0.009952
1,1.0,0.411561,0.447439,0.457733,0.628209,0.625724,0.880983,0.555418,0.533724,0.443784,...,0.680432,0.003151,0.459534,0.628201,0.850553,0.060711,0.261897,0.530599,0.0,0.023846
2,1.0,0.478649,0.535214,0.522298,0.697649,0.694889,0.913320,0.577930,0.555996,0.449630,...,0.753743,0.003776,0.462408,0.697648,0.892175,0.032330,0.242818,0.580957,0.0,0.045126
3,1.0,0.400070,0.411100,0.419134,0.658415,0.656169,0.887885,0.551820,0.520878,0.432889,...,0.641922,0.005177,0.457961,0.658427,0.813014,0.090494,0.261688,0.530023,0.0,0.015621
4,0.0,0.402378,0.441840,0.436158,0.794077,0.790935,0.915685,0.557954,0.533381,0.418841,...,0.676552,0.018272,0.463062,0.794080,0.813336,0.156123,0.261168,0.528468,0.0,0.008462

In [10]:
df_scaled['Bankrupt']=df_scaled['Bankrupt'].astype('int64')

In [11]:
df_scaled.head()

,Bankrupt,ROA(C)_before_interest_and_depreciation_before_interest,ROA(A)_before_interest_and_%_after_tax,ROA(B)_before_interest_and_depreciation_after_tax,Operating_Gross_Margin,Realized_Sales_Gross_Margin,Operating_Profit_Rate,Pre-tax_net_Interest_Rate,After-tax_net_Interest_Rate,Non-industry_income_and_expenditure/revenue,...,Net_Income_to_Total_Assets,Total_assets_to_GNP_price,No-credit_Interval,Gross_Profit_to_Sales,Net_Income_to_Stockholder's_Equity,Liability_to_Equity,Degree_of_Financial_Leverage_(DFL),Interest_Coverage_Ratio_(Interest_expense_to_EBIT),Net_Income_Flag,Equity_to_Liability
0,1,0.381454,0.420377,0.405750,0.709830,0.707021,0.912856,0.550915,0.523433,0.411011,...,0.650414,0.009119,0.459292,0.709820,0.796851,0.135752,0.260955,0.527779,0.0,0.009952
1,1,0.411561,0.447439,0.457733,0.628209,0.625724,0.880983,0.555418,0.533724,0.443784,...,0.680432,0.003151,0.459534,0.628201,0.850553,0.060711,0.261897,0.530599,0.0,0.023846
2,1,0.478649,0.535214,0.522298,0.697649,0.694889,0.913320,0.577930,0.555996,0.449630,...,0.753743,0.003776,0.462408,0.697648,0.892175,0.032330,0.242818,0.580957,0.0,0.045126
3,1,0.400070,0.411100,0.419134,0.658415,0.656169,0.887885,0.551820,0.520878,0.432889,...,0.641922,0.005177,0.457961,0.658427,0.813014,0.090494,0.261688,0.530023,0.0,0.015621
4,0,0.402378,0.441840,0.436158,0.794077,0.790935,0.915685,0.557954,0.533381,0.418841,...,0.676552,0.018272,0.463062,0.794080,0.813336,0.156123,0.261168,0.528468,0.0,0.008462

In [12]:
df_scaled['Bankrupt'].value_counts()

0    6369
1     183
Name: Bankrupt, dtype: int64

In [15]:
df_scaled.to_csv("datapreprocessed.csv")